# fly.toml file generated for os4320-project on 2023-05-02T21:43:20-04:00

app = "os4320-project"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
